version: '3.5'

services:
  symfony-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: app
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - XDEBUG_CONFIG=remote_host=172.17.0.1
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

networks:
  backend:
    name: backend-network
